package org.mobilenativefoundation.trails.server.fake.internal.seed

import org.mobilenativefoundation.trails.server.model.BackgroundGradientId
import org.mobilenativefoundation.trails.server.model.EmojiId
import org.mobilenativefoundation.trails.server.model.TrailDifficulty
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredFollow
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredPost
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredResort
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredRun
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredUser
import org.mobilenativefoundation.trails.server.fake.internal.storage.StoredWeather

internal class DefaultSeedData {
    val users: List<StoredUser> = listOf(
        StoredUser(
            id = "author_matt",
            email = "matt@example.com",
            passwordHash = "hashed_password",
            firstName = "Matt",
            lastName = null,
            birthdate = null,
            displayName = "Matt",
            username = "matt",
            avatarUrl = "https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2tpfGVufDB8fDB8fHww",
            bio = null,
            location = null,
            verified = true,
            createdAt = 1704067200000,
            version = 1,
        ),
        StoredUser(
            id = "author_lily",
            email = "lily@example.com",
            passwordHash = "hashed_password",
            firstName = "Lily",
            lastName = null,
            birthdate = null,
            displayName = "Lily",
            username = "lily",
            avatarUrl = "https://images.unsplash.com/photo-1486684338211-1a7ced564b0d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHNraXxlbnwwfHwwfHx8MA%3D%3D",
            bio = null,
            location = null,
            verified = false,
            createdAt = 1704067200000,
            version = 1,
        ),
        StoredUser(
            id = "author_ty",
            email = "ty@example.com",
            passwordHash = "hashed_password",
            firstName = "Ty",
            lastName = null,
            birthdate = null,
            displayName = "Ty",
            username = "ty",
            avatarUrl = "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8c2tpfGVufDB8fDB8fHww",
            bio = null,
            location = null,
            verified = true,
            createdAt = 1704067200000,
            version = 1,
        ),
        StoredUser(
            id = "author_bryce",
            email = "bryce@example.com",
            passwordHash = "hashed_password",
            firstName = "Bryce",
            lastName = null,
            birthdate = null,
            displayName = "Bryce",
            username = "bryce",
            avatarUrl = "https://images.unsplash.com/photo-1596473537047-50758f115d04?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fHNraXxlbnwwfHwwfHx8MA%3D%3D",
            bio = null,
            location = null,
            verified = false,
            createdAt = 1704067200000,
            version = 1,
        ),
    )

    val resorts: List<StoredResort> = listOf(
        StoredResort(
            id = "resort_aspen_snowmass",
            name = "Aspen Snowmass",
            city = "Aspen",
            state = "CO",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2300,
            runs = 1,
            lifts = 1,
            verticalFeet = 2300,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_beaver_creek",
            name = "Beaver Creek",
            city = "Avon",
            state = null,
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2470,
            runs = 1,
            lifts = 1,
            verticalFeet = 2470,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_catedral_alta_patagonia",
            name = "Catedral Alta Patagonia",
            city = "San Carlos de Bariloche",
            state = null,
            country = "Argentina",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2600,
            runs = 1,
            lifts = 1,
            verticalFeet = 2600,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_cervinia",
            name = "Cervinia",
            city = "Breuil-Cervinia",
            state = null,
            country = "Italy",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1800,
            runs = 1,
            lifts = 1,
            verticalFeet = 1800,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_chamonix_mont_blanc",
            name = "Chamonix Mont-Blanc",
            city = "Chamonix",
            state = null,
            country = "France",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 9200,
            runs = 1,
            lifts = 1,
            verticalFeet = 9200,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_cortina_d_ampezzo",
            name = "Cortina d'Ampezzo",
            city = "Cortina d'Ampezzo",
            state = null,
            country = "Italy",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2800,
            runs = 1,
            lifts = 1,
            verticalFeet = 2800,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_happo_one",
            name = "Happo-One",
            city = "Hakuba",
            state = null,
            country = "Japan",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2600,
            runs = 1,
            lifts = 1,
            verticalFeet = 2600,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_jackson_hole",
            name = "Jackson Hole",
            city = "Teton Village",
            state = "WY",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1950,
            runs = 2,
            lifts = 2,
            verticalFeet = 1950,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 2,
            runsOpen = 2,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_killington",
            name = "Killington",
            city = "Killington",
            state = "VT",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1500,
            runs = 1,
            lifts = 1,
            verticalFeet = 1500,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_kitzb_hel",
            name = "Kitzbühel",
            city = "Kitzbühel",
            state = null,
            country = "Austria",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2830,
            runs = 1,
            lifts = 1,
            verticalFeet = 2830,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_mammoth",
            name = "Mammoth",
            city = "Mammoth Lakes",
            state = "CA",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 980,
            runs = 1,
            lifts = 1,
            verticalFeet = 980,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_mayrhofen",
            name = "Mayrhofen",
            city = "Mayrhofen",
            state = null,
            country = "Austria",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1250,
            runs = 1,
            lifts = 1,
            verticalFeet = 1250,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_palisades_tahoe",
            name = "Palisades Tahoe",
            city = "Olympic Valley",
            state = "CA",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1800,
            runs = 1,
            lifts = 1,
            verticalFeet = 1800,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_park_city",
            name = "Park City",
            city = "Park City",
            state = "UT",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1200,
            runs = 1,
            lifts = 1,
            verticalFeet = 1200,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_st_moritz",
            name = "St. Moritz",
            city = "St. Moritz",
            state = null,
            country = "Switzerland",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 2100,
            runs = 1,
            lifts = 1,
            verticalFeet = 2100,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_taos_ski_valley",
            name = "Taos Ski Valley",
            city = "Taos",
            state = "NM",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1100,
            runs = 1,
            lifts = 1,
            verticalFeet = 1100,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_vail",
            name = "Vail",
            city = "Vail",
            state = "CO",
            country = "USA",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 3050,
            runs = 2,
            lifts = 2,
            verticalFeet = 3050,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 2,
            runsOpen = 2,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_wengen_grindelwald",
            name = "Wengen-Grindelwald",
            city = "Wengen",
            state = null,
            country = "Switzerland",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 3280,
            runs = 1,
            lifts = 1,
            verticalFeet = 3280,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_whistler_blackcomb",
            name = "Whistler Blackcomb",
            city = "Whistler",
            state = null,
            country = "Canada",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 1500,
            runs = 1,
            lifts = 1,
            verticalFeet = 1500,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
        StoredResort(
            id = "resort_zermatt",
            name = "Zermatt",
            city = "Zermatt",
            state = null,
            country = "Switzerland",
            latitude = 0.0,
            longitude = 0.0,
            elevation = 3600,
            runs = 1,
            lifts = 1,
            verticalFeet = 3600,
            skiableAcres = 0,
            snowfallAnnualInches = 0,
            amenities = emptyList(),
            isOpen = true,
            liftsOpen = 1,
            runsOpen = 1,
            imageUrl = null,
            version = 1,
        ),
    )

    val runs: List<StoredRun> = listOf(
        StoredRun(
            id = "run_killington_superstar",
            resortId = "resort_killington",
            name = "Superstar",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 1.0f,
            verticalFeet = 1500,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Superstar Express"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_beaver_creek_birds_of_prey",
            resortId = "resort_beaver_creek",
            name = "Birds of Prey",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 2470,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Centennial Express"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_vail_riva_ridge",
            resortId = "resort_vail",
            name = "Riva Ridge",
            difficulty = TrailDifficulty.BLUE_SQUARE,
            lengthMiles = 4.0f,
            verticalFeet = 3050,
            averageGradePct = 18,
            maxGradePct = 25,
            isOpen = true,
            conditions = "Groomed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Riva Bahn Express"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_vail_blue_sky_basin_pete_s_bowl",
            resortId = "resort_vail",
            name = "Blue Sky Basin - Pete's Bowl",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 1.0f,
            verticalFeet = 1200,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Skyline Express"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_zermatt_matterhorn_glacier_run",
            resortId = "resort_zermatt",
            name = "Matterhorn Glacier Run",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 3600,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Matterhorn Glacier Paradise"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_cortina_d_ampezzo_tofana_schuss",
            resortId = "resort_cortina_d_ampezzo",
            name = "Tofana Schuss",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 2800,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Freccia nel Cielo"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_catedral_alta_patagonia_la_gran_pista",
            resortId = "resort_catedral_alta_patagonia",
            name = "La Gran Pista",
            difficulty = TrailDifficulty.BLUE_SQUARE,
            lengthMiles = 3.0f,
            verticalFeet = 2600,
            averageGradePct = 18,
            maxGradePct = 25,
            isOpen = true,
            conditions = "Groomed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Punta Nevada"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_happo_one_olympic_course",
            resortId = "resort_happo_one",
            name = "Olympic Course",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 2600,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Happo Gondola"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_palisades_tahoe_kt_22",
            resortId = "resort_palisades_tahoe",
            name = "KT-22",
            difficulty = TrailDifficulty.DOUBLE_BLACK,
            lengthMiles = 1.0f,
            verticalFeet = 1800,
            averageGradePct = 32,
            maxGradePct = 40,
            isOpen = true,
            conditions = "Wind buff",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("KT-22 Express"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_whistler_blackcomb_blackcomb_glacier",
            resortId = "resort_whistler_blackcomb",
            name = "Blackcomb Glacier",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 1500,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Showcase T-Bar"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_chamonix_mont_blanc_vall_e_blanche",
            resortId = "resort_chamonix_mont_blanc",
            name = "Vallée Blanche",
            difficulty = TrailDifficulty.DOUBLE_BLACK,
            lengthMiles = 13.0f,
            verticalFeet = 9200,
            averageGradePct = 32,
            maxGradePct = 40,
            isOpen = true,
            conditions = "Wind buff",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Aiguille du Midi Cable Car"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_st_moritz_corviglia_fis_world_cup_run",
            resortId = "resort_st_moritz",
            name = "Corviglia FIS World Cup Run",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 2.0f,
            verticalFeet = 2100,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Corviglia Funicular"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_jackson_hole_corbet_s_couloir",
            resortId = "resort_jackson_hole",
            name = "Corbet's Couloir",
            difficulty = TrailDifficulty.DOUBLE_BLACK,
            lengthMiles = 1.0f,
            verticalFeet = 500,
            averageGradePct = 32,
            maxGradePct = 40,
            isOpen = true,
            conditions = "Wind buff",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Aerial Tram"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_mayrhofen_harakiri",
            resortId = "resort_mayrhofen",
            name = "Harakiri",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 1.0f,
            verticalFeet = 1250,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Penken Gondola"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_kitzb_hel_streif",
            resortId = "resort_kitzb_hel",
            name = "Streif",
            difficulty = TrailDifficulty.DOUBLE_BLACK,
            lengthMiles = 2.0f,
            verticalFeet = 2830,
            averageGradePct = 32,
            maxGradePct = 40,
            isOpen = true,
            conditions = "Wind buff",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Hahnenkamm Cable Car"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_wengen_grindelwald_lauberhorn",
            resortId = "resort_wengen_grindelwald",
            name = "Lauberhorn",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 3.0f,
            verticalFeet = 3280,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Lauberhorn Lift"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_cervinia_prima_neve",
            resortId = "resort_cervinia",
            name = "Prima Neve",
            difficulty = TrailDifficulty.BLUE_SQUARE,
            lengthMiles = 2.0f,
            verticalFeet = 1800,
            averageGradePct = 18,
            maxGradePct = 25,
            isOpen = true,
            conditions = "Groomed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Plan Maison Gondola"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_taos_ski_valley_al_s_run",
            resortId = "resort_taos_ski_valley",
            name = "Al's Run",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 1.0f,
            verticalFeet = 1100,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Lift 2"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_aspen_snowmass_north_face_express",
            resortId = "resort_aspen_snowmass",
            name = "North Face Express",
            difficulty = TrailDifficulty.BLACK_DIAMOND,
            lengthMiles = 4.8f,
            verticalFeet = 2300,
            averageGradePct = 28,
            maxGradePct = 35,
            isOpen = true,
            conditions = "Packed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Gondola"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_jackson_hole_highline_bowl",
            resortId = "resort_jackson_hole",
            name = "Highline Bowl",
            difficulty = TrailDifficulty.DOUBLE_BLACK,
            lengthMiles = 3.1f,
            verticalFeet = 1950,
            averageGradePct = 32,
            maxGradePct = 40,
            isOpen = true,
            conditions = "Wind buff",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Tram"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_park_city_bluebird_cruiser",
            resortId = "resort_park_city",
            name = "Bluebird Cruiser",
            difficulty = TrailDifficulty.BLUE_SQUARE,
            lengthMiles = 6.2f,
            verticalFeet = 1200,
            averageGradePct = 18,
            maxGradePct = 25,
            isOpen = true,
            conditions = "Groomed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("Express Quad"),
            features = emptyList(),
            version = 1,
        ),
        StoredRun(
            id = "run_mammoth_sunrise_glades",
            resortId = "resort_mammoth",
            name = "Sunrise Glades",
            difficulty = TrailDifficulty.GREEN_CIRCLE,
            lengthMiles = 2.6f,
            verticalFeet = 980,
            averageGradePct = 12,
            maxGradePct = 18,
            isOpen = true,
            conditions = "Groomed",
            lastGroomed = "2025-01-11T06:00:00Z",
            liftAccess = listOf("High Speed Six"),
            features = emptyList(),
            version = 1,
        ),
    )

    val weather: List<StoredWeather> = listOf(
        StoredWeather(
            resortId = "resort_aspen_snowmass",
            observedAt = 1736593200000,
            conditions = "Powder",
            temperatureF = 18,
            feelsLikeF = 17,
            windMph = 9,
            windDirection = "SW",
            humidity = 65,
            visibility = "good",
            uvIndex = 3,
            newSnow24h = 5,
            newSnow48h = 10,
            newSnow7d = 25,
            baseDepth = 65,
            seasonTotal = 235,
        ),
        StoredWeather(
            resortId = "resort_beaver_creek",
            observedAt = 1736582400000,
            conditions = "Groomed",
            temperatureF = 10,
            feelsLikeF = 6,
            windMph = 18,
            windDirection = "N",
            humidity = 32,
            visibility = "good",
            uvIndex = 6,
            newSnow24h = 2,
            newSnow48h = 7,
            newSnow7d = 22,
            baseDepth = 92,
            seasonTotal = 302,
        ),
        StoredWeather(
            resortId = "resort_catedral_alta_patagonia",
            observedAt = 1736582400000,
            conditions = "Groomed",
            temperatureF = 25,
            feelsLikeF = 23,
            windMph = 10,
            windDirection = "E",
            humidity = 72,
            visibility = "good",
            uvIndex = 4,
            newSnow24h = 2,
            newSnow48h = 2,
            newSnow7d = 2,
            baseDepth = 42,
            seasonTotal = 192,
        ),
        StoredWeather(
            resortId = "resort_cervinia",
            observedAt = 1736600400000,
            conditions = "Groomed",
            temperatureF = 20,
            feelsLikeF = 15,
            windMph = 17,
            windDirection = "NE",
            humidity = 67,
            visibility = "good",
            uvIndex = 7,
            newSnow24h = 7,
            newSnow48h = 2,
            newSnow7d = 17,
            baseDepth = 57,
            seasonTotal = 287,
        ),
        StoredWeather(
            resortId = "resort_chamonix_mont_blanc",
            observedAt = 1736586000000,
            conditions = "Wind buff",
            temperatureF = 21,
            feelsLikeF = 20,
            windMph = 25,
            windDirection = "NW",
            humidity = 43,
            visibility = "moderate",
            uvIndex = 3,
            newSnow24h = 3,
            newSnow48h = 13,
            newSnow7d = 13,
            baseDepth = 83,
            seasonTotal = 213,
        ),
        StoredWeather(
            resortId = "resort_cortina_d_ampezzo",
            observedAt = 1736589600000,
            conditions = "Icy",
            temperatureF = 32,
            feelsLikeF = 32,
            windMph = 22,
            windDirection = "S",
            humidity = 54,
            visibility = "moderate",
            uvIndex = 2,
            newSnow24h = 4,
            newSnow48h = 9,
            newSnow7d = 24,
            baseDepth = 64,
            seasonTotal = 274,
        ),
        StoredWeather(
            resortId = "resort_happo_one",
            observedAt = 1736593200000,
            conditions = "Powder",
            temperatureF = 13,
            feelsLikeF = 8,
            windMph = 23,
            windDirection = "NE",
            humidity = 35,
            visibility = "good",
            uvIndex = 7,
            newSnow24h = 5,
            newSnow48h = 5,
            newSnow7d = 5,
            baseDepth = 45,
            seasonTotal = 255,
        ),
        StoredWeather(
            resortId = "resort_jackson_hole",
            observedAt = 1736582400000,
            conditions = "Groomed",
            temperatureF = 10,
            feelsLikeF = 8,
            windMph = 6,
            windDirection = "E",
            humidity = 32,
            visibility = "good",
            uvIndex = 4,
            newSnow24h = 2,
            newSnow48h = 2,
            newSnow7d = 2,
            baseDepth = 42,
            seasonTotal = 152,
        ),
        StoredWeather(
            resortId = "resort_killington",
            observedAt = 1736593200000,
            conditions = "Powder",
            temperatureF = 23,
            feelsLikeF = 22,
            windMph = 5,
            windDirection = "SE",
            humidity = 45,
            visibility = "good",
            uvIndex = 3,
            newSnow24h = 5,
            newSnow48h = 10,
            newSnow7d = 25,
            baseDepth = 95,
            seasonTotal = 265,
        ),
        StoredWeather(
            resortId = "resort_kitzb_hel",
            observedAt = 1736575200000,
            conditions = "Powder",
            temperatureF = 23,
            feelsLikeF = 21,
            windMph = 22,
            windDirection = "N",
            humidity = 70,
            visibility = "good",
            uvIndex = 4,
            newSnow24h = 0,
            newSnow48h = 5,
            newSnow7d = 20,
            baseDepth = 60,
            seasonTotal = 190,
        ),
        StoredWeather(
            resortId = "resort_mammoth",
            observedAt = 1736600400000,
            conditions = "Groomed",
            temperatureF = 15,
            feelsLikeF = 14,
            windMph = 17,
            windDirection = "NE",
            humidity = 37,
            visibility = "good",
            uvIndex = 3,
            newSnow24h = 7,
            newSnow48h = 7,
            newSnow7d = 7,
            baseDepth = 77,
            seasonTotal = 207,
        ),
        StoredWeather(
            resortId = "resort_mayrhofen",
            observedAt = 1736607600000,
            conditions = "Icy",
            temperatureF = 32,
            feelsLikeF = 29,
            windMph = 7,
            windDirection = "SE",
            humidity = 79,
            visibility = "moderate",
            uvIndex = 5,
            newSnow24h = 9,
            newSnow48h = 9,
            newSnow7d = 9,
            baseDepth = 79,
            seasonTotal = 249,
        ),
        StoredWeather(
            resortId = "resort_palisades_tahoe",
            observedAt = 1736596800000,
            conditions = "Packed",
            temperatureF = 29,
            feelsLikeF = 25,
            windMph = 20,
            windDirection = "E",
            humidity = 76,
            visibility = "good",
            uvIndex = 6,
            newSnow24h = 6,
            newSnow48h = 1,
            newSnow7d = 16,
            baseDepth = 86,
            seasonTotal = 296,
        ),
        StoredWeather(
            resortId = "resort_park_city",
            observedAt = 1736596800000,
            conditions = "Packed",
            temperatureF = 29,
            feelsLikeF = 29,
            windMph = 24,
            windDirection = "W",
            humidity = 76,
            visibility = "good",
            uvIndex = 2,
            newSnow24h = 6,
            newSnow48h = 6,
            newSnow7d = 6,
            baseDepth = 46,
            seasonTotal = 196,
        ),
        StoredWeather(
            resortId = "resort_st_moritz",
            observedAt = 1736586000000,
            conditions = "Wind buff",
            temperatureF = 11,
            feelsLikeF = 6,
            windMph = 23,
            windDirection = "NW",
            humidity = 33,
            visibility = "moderate",
            uvIndex = 7,
            newSnow24h = 3,
            newSnow48h = 8,
            newSnow7d = 23,
            baseDepth = 63,
            seasonTotal = 253,
        ),
        StoredWeather(
            resortId = "resort_taos_ski_valley",
            observedAt = 1736593200000,
            conditions = "Powder",
            temperatureF = 23,
            feelsLikeF = 18,
            windMph = 15,
            windDirection = "SW",
            humidity = 45,
            visibility = "good",
            uvIndex = 7,
            newSnow24h = 5,
            newSnow48h = 5,
            newSnow7d = 5,
            baseDepth = 45,
            seasonTotal = 315,
        ),
        StoredWeather(
            resortId = "resort_vail",
            observedAt = 1736582400000,
            conditions = "Groomed",
            temperatureF = 10,
            feelsLikeF = 10,
            windMph = 24,
            windDirection = "S",
            humidity = 32,
            visibility = "good",
            uvIndex = 2,
            newSnow24h = 2,
            newSnow48h = 12,
            newSnow7d = 12,
            baseDepth = 52,
            seasonTotal = 202,
        ),
        StoredWeather(
            resortId = "resort_wengen_grindelwald",
            observedAt = 1736582400000,
            conditions = "Groomed",
            temperatureF = 20,
            feelsLikeF = 20,
            windMph = 18,
            windDirection = "S",
            humidity = 42,
            visibility = "good",
            uvIndex = 2,
            newSnow24h = 2,
            newSnow48h = 12,
            newSnow7d = 12,
            baseDepth = 52,
            seasonTotal = 162,
        ),
        StoredWeather(
            resortId = "resort_whistler_blackcomb",
            observedAt = 1736578800000,
            conditions = "Packed",
            temperatureF = 29,
            feelsLikeF = 26,
            windMph = 11,
            windDirection = "NW",
            humidity = 51,
            visibility = "good",
            uvIndex = 5,
            newSnow24h = 1,
            newSnow48h = 6,
            newSnow7d = 21,
            baseDepth = 91,
            seasonTotal = 221,
        ),
        StoredWeather(
            resortId = "resort_zermatt",
            observedAt = 1736607600000,
            conditions = "Icy",
            temperatureF = 22,
            feelsLikeF = 19,
            windMph = 19,
            windDirection = "SW",
            humidity = 69,
            visibility = "moderate",
            uvIndex = 5,
            newSnow24h = 9,
            newSnow48h = 9,
            newSnow7d = 9,
            baseDepth = 49,
            seasonTotal = 339,
        ),
    )

    val posts: List<StoredPost> = listOf(
        StoredPost(
            id = "post_run_killington_superstar",
            authorId = "author_bryce",
            runId = "run_killington_superstar",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736424000000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_beaver_creek_birds_of_prey",
            authorId = "author_matt",
            runId = "run_beaver_creek_birds_of_prey",
            backgroundGradientId = BackgroundGradientId("INDIGO_BLUE_CYAN"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736578800000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_vail_riva_ridge",
            authorId = "author_bryce",
            runId = "run_vail_riva_ridge",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736593200000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_vail_blue_sky_basin_pete_s_bowl",
            authorId = "author_bryce",
            runId = "run_vail_blue_sky_basin_pete_s_bowl",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736510400000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_zermatt_matterhorn_glacier_run",
            authorId = "author_matt",
            runId = "run_zermatt_matterhorn_glacier_run",
            backgroundGradientId = BackgroundGradientId("INDIGO_BLUE_CYAN"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736424000000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_cortina_d_ampezzo_tofana_schuss",
            authorId = "author_ty",
            runId = "run_cortina_d_ampezzo_tofana_schuss",
            backgroundGradientId = BackgroundGradientId("SKY_CYAN_BLUE"),
            emojiId = EmojiId("AerialTramway"),
            caption = null,
            createdAt = 1736424000000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_catedral_alta_patagonia_la_gran_pista",
            authorId = "author_bryce",
            runId = "run_catedral_alta_patagonia_la_gran_pista",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736571600000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_happo_one_olympic_course",
            authorId = "author_lily",
            runId = "run_happo_one_olympic_course",
            backgroundGradientId = BackgroundGradientId("BLUE_INDIGO_PURPLE"),
            emojiId = EmojiId("SnowCappedMountain"),
            caption = null,
            createdAt = 1736593200000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_palisades_tahoe_kt_22",
            authorId = "author_bryce",
            runId = "run_palisades_tahoe_kt_22",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736589600000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_whistler_blackcomb_blackcomb_glacier",
            authorId = "author_ty",
            runId = "run_whistler_blackcomb_blackcomb_glacier",
            backgroundGradientId = BackgroundGradientId("SKY_CYAN_BLUE"),
            emojiId = EmojiId("AerialTramway"),
            caption = null,
            createdAt = 1736593200000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_chamonix_mont_blanc_vall_e_blanche",
            authorId = "author_bryce",
            runId = "run_chamonix_mont_blanc_vall_e_blanche",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736578800000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_st_moritz_corviglia_fis_world_cup_run",
            authorId = "author_lily",
            runId = "run_st_moritz_corviglia_fis_world_cup_run",
            backgroundGradientId = BackgroundGradientId("BLUE_INDIGO_PURPLE"),
            emojiId = EmojiId("SnowCappedMountain"),
            caption = null,
            createdAt = 1736578800000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_jackson_hole_corbet_s_couloir",
            authorId = "author_matt",
            runId = "run_jackson_hole_corbet_s_couloir",
            backgroundGradientId = BackgroundGradientId("INDIGO_BLUE_CYAN"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736571600000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_mayrhofen_harakiri",
            authorId = "author_lily",
            runId = "run_mayrhofen_harakiri",
            backgroundGradientId = BackgroundGradientId("BLUE_INDIGO_PURPLE"),
            emojiId = EmojiId("SnowCappedMountain"),
            caption = null,
            createdAt = 1736578800000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_kitzb_hel_streif",
            authorId = "author_ty",
            runId = "run_kitzb_hel_streif",
            backgroundGradientId = BackgroundGradientId("SKY_CYAN_BLUE"),
            emojiId = EmojiId("AerialTramway"),
            caption = null,
            createdAt = 1736424000000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_wengen_grindelwald_lauberhorn",
            authorId = "author_lily",
            runId = "run_wengen_grindelwald_lauberhorn",
            backgroundGradientId = BackgroundGradientId("BLUE_INDIGO_PURPLE"),
            emojiId = EmojiId("SnowCappedMountain"),
            caption = null,
            createdAt = 1736424000000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_cervinia_prima_neve",
            authorId = "author_ty",
            runId = "run_cervinia_prima_neve",
            backgroundGradientId = BackgroundGradientId("SKY_CYAN_BLUE"),
            emojiId = EmojiId("AerialTramway"),
            caption = null,
            createdAt = 1736589600000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
        StoredPost(
            id = "post_run_taos_ski_valley_al_s_run",
            authorId = "author_bryce",
            runId = "run_taos_ski_valley_al_s_run",
            backgroundGradientId = BackgroundGradientId("CYAN_BLUE_INDIGO"),
            emojiId = EmojiId("Skier"),
            caption = null,
            createdAt = 1736578800000,
            version = 1,
            likes = 0,
            comments = 0,
            shares = 0,
            views = 0,
        ),
    )

    val follows: List<StoredFollow> = listOf(
        StoredFollow(
            followerId = "author_matt",
            followeeId = "author_lily",
            createdAt = 1704067200000,
        ),
    )
}
